#!/usr/bin/env python
"""
GITV Vertical 4-Panel Manga Builder (Official Script)
=====================================================
Workflow:
1. Takes a raw 4-panel image (generated by AI without any text or speech bubbles).
2. Crops the 4 individual panels (stripping away messy AI borders).
3. Arranges them into a clean, mobile-optimized vertical 1-column layout.
4. Auto-fits crisp vector speech bubbles based on text length and line breaks.
5. Accurately aims short vector tails (atan2) toward characters' heads.
6. Renders production-ready SVG and rasterizes to PNG via Edge headless browser.

Usage:
  python scripts/koneta/build_vertical_manga.py \
      --image workbench/candidates/article-images/sample-raw.jpg \
      --spec config/koneta/episodes/sample.json \
      --output content/attachments/sample.png \
      [--svg-output content/attachments/sample.svg]
"""

import sys
import os
import math
import json
import base64
import argparse
import subprocess
from pathlib import Path
from PIL import Image
import numpy as np

# Windows UTF-8 stdout
if sys.platform == "win32":
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")


def detect_or_default_boxes(im, inset=4):
    """
    Detects the 4 inner panel rectangles in a 2x2 raw AI-generated manga image.
    Accurately strips the outer white margins, outer black borders, and center gutters.
    Applies an inner inset so no residual borders or gutter slivers bleed into the panels.
    """
    w, h = im.size
    arr = np.array(im)

    # Calculate row and col mean brightness
    row_means = arr.mean(axis=(1, 2))
    col_means = arr.mean(axis=(0, 2))

    # Outer borders detection (search for dark border lines near edges)
    top_darks = [y for y in range(8, int(h * 0.08)) if row_means[y] < 60]
    bottom_darks = [y for y in range(int(h * 0.92), h - 8) if row_means[y] < 60]
    left_darks = [x for x in range(8, int(w * 0.08)) if col_means[x] < 60]
    right_darks = [x for x in range(int(w * 0.92), w - 8) if col_means[x] < 60]

    outer_top = (max(top_darks) + inset) if top_darks else int(h * 0.035)
    outer_bottom = (min(bottom_darks) - inset) if bottom_darks else int(h * 0.965)
    outer_left = (max(left_darks) + inset) if left_darks else int(w * 0.035)
    outer_right = (min(right_darks) - inset) if right_darks else int(w * 0.965)

    # Center gutters detection (search around midpoints 44% - 56%)
    mid_y_darks = [y for y in range(int(h * 0.44), int(h * 0.56)) if row_means[y] < 60]
    mid_x_darks = [x for x in range(int(w * 0.44), int(w * 0.56)) if col_means[x] < 60]

    # If center dark borders exist around the gutter
    if len(mid_y_darks) >= 2 and len(mid_x_darks) >= 2:
        cy_top = min(mid_y_darks) - inset
        cy_bottom = max(mid_y_darks) + inset
        cx_left = min(mid_x_darks) - inset
        cx_right = max(mid_x_darks) + inset

        b1 = (outer_left, outer_top, cx_left, cy_top)
        b2 = (cx_right, outer_top, outer_right, cy_top)
        b3 = (outer_left, cy_bottom, cx_left, outer_bottom)
        b4 = (cx_right, cy_bottom, outer_right, outer_bottom)
    else:
        # Robust fallback with 3.5% outer margin and 3% center gutter
        mx = int(w * 0.035)
        my = int(h * 0.035)
        gw = int(w * 0.03)
        gh = int(h * 0.03)
        pw = (w - mx * 2 - gw) // 2
        ph = (h - my * 2 - gh) // 2

        b1 = (mx, my, mx + pw, my + ph)
        b2 = (mx + pw + gw, my, mx + pw * 2 + gw, my + ph)
        b3 = (mx, my + ph + gh, mx + pw, my + ph * 2 + gh)
        b4 = (mx + pw + gw, my + ph + gh, mx + pw * 2 + gw, my + ph * 2 + gh)

    return [b1, b2, b3, b4]


def crop_panels_to_b64(raw_image_path):
    """Crops the raw image into 4 panels and returns base64 strings."""
    im = Image.open(raw_image_path).convert("RGB")
    boxes = detect_or_default_boxes(im)

    b64_list = []
    for i, box in enumerate(boxes):
        cropped = im.crop(box)
        # In-memory buffer
        from io import BytesIO
        buf = BytesIO()
        cropped.save(buf, format="PNG")
        b64 = f"data:image/png;base64,{base64.b64encode(buf.getvalue()).decode('ascii')}"
        b64_list.append(b64)
    return b64_list


def estimate_text_width(text, font_size=20):
    """Accurately calculates display pixel width for Japanese & ASCII characters."""
    w = 0.0
    for ch in text:
        if ord(ch) > 127:
            w += font_size * 1.05  # Fullwidth Japanese char
        else:
            w += font_size * 0.58  # Halfwidth ASCII char
    return int(w)


def generate_speech_bubble(lines_spec, bx, by, target_x, target_y, tail_side="auto", tail_len=26, radius=16, font_size=20, line_height=30):
    """
    Auto-fits bubble dimensions from text length and lines,
    and dynamically aims a short vector tail toward (target_x, target_y).
    """
    raw_lines = [item['text'] for item in lines_spec]
    max_text_w = max(estimate_text_width(l, font_size) for l in raw_lines) if raw_lines else 100
    pad_x = 28
    pad_y = 16
    bw = max_text_w + pad_x * 2
    bh = len(raw_lines) * line_height + pad_y * 2

    # Determine tail anchor edge
    if tail_side == "auto":
        if target_x > bx + bw + 20 and by - 20 <= target_y <= by + bh + 120:
            tail_side = "right"
        elif target_x < bx - 20 and by - 20 <= target_y <= by + bh + 120:
            tail_side = "left"
        else:
            tail_side = "bottom"

    r = radius
    d = []

    if tail_side == "bottom":
        ax = max(bx + r + 24, min(bx + bw - r - 24, target_x))
        ay = by + bh
        angle = math.atan2(target_y - ay, target_x - ax)
        tip_x = ax + tail_len * math.cos(angle)
        tip_y = ay + tail_len * math.sin(angle)

        rw = 12
        base_left = ax - rw
        base_right = ax + rw

        d.append(f"M {bx + r} {by}")
        d.append(f"H {bx + bw - r}")
        d.append(f"A {r} {r} 0 0 1 {bx + bw} {by + r}")
        d.append(f"V {by + bh - r}")
        d.append(f"A {r} {r} 0 0 1 {bx + bw - r} {by + bh}")
        d.append(f"H {base_right}")
        d.append(f"Q {ax + rw*0.3} {ay + tail_len*0.4} {tip_x:.1f} {tip_y:.1f}")
        d.append(f"Q {ax - rw*0.3} {ay + tail_len*0.4} {base_left} {ay}")
        d.append(f"H {bx + r}")
        d.append(f"A {r} {r} 0 0 1 {bx} {by + bh - r}")
        d.append(f"V {by + r}")
        d.append(f"A {r} {r} 0 0 1 {bx + r} {by}")
        d.append("Z")

    elif tail_side == "right":
        ax = bx + bw
        ay = max(by + r + 20, min(by + bh - r - 20, target_y))
        eff_tx = max(ax + 10, target_x)
        angle = math.atan2(target_y - ay, eff_tx - ax)
        tip_x = ax + tail_len * math.cos(angle)
        tip_y = ay + tail_len * math.sin(angle)

        rw = 12
        base_top = ay - rw
        base_bottom = ay + rw

        d.append(f"M {bx + r} {by}")
        d.append(f"H {bx + bw - r}")
        d.append(f"A {r} {r} 0 0 1 {bx + bw} {by + r}")
        d.append(f"V {base_top}")
        d.append(f"Q {ax + tail_len*0.4} {ay - rw*0.3} {tip_x:.1f} {tip_y:.1f}")
        d.append(f"Q {ax + tail_len*0.4} {ay + rw*0.3} {ax} {base_bottom}")
        d.append(f"V {by + bh - r}")
        d.append(f"A {r} {r} 0 0 1 {bx + bw - r} {by + bh}")
        d.append(f"H {bx + r}")
        d.append(f"A {r} {r} 0 0 1 {bx} {by + bh - r}")
        d.append(f"V {by + r}")
        d.append(f"A {r} {r} 0 0 1 {bx + r} {by}")
        d.append("Z")

    elif tail_side == "left":
        ax = bx
        ay = max(by + r + 20, min(by + bh - r - 20, target_y))
        eff_tx = min(ax - 10, target_x)
        angle = math.atan2(target_y - ay, eff_tx - ax)
        tip_x = ax + tail_len * math.cos(angle)
        tip_y = ay + tail_len * math.sin(angle)


        rw = 12
        base_top = ay - rw
        base_bottom = ay + rw

        d.append(f"M {bx + r} {by}")
        d.append(f"H {bx + bw - r}")
        d.append(f"A {r} {r} 0 0 1 {bx + bw} {by + r}")
        d.append(f"V {by + bh - r}")
        d.append(f"A {r} {r} 0 0 1 {bx + bw - r} {by + bh}")
        d.append(f"H {bx + r}")
        d.append(f"A {r} {r} 0 0 1 {bx} {by + bh - r}")
        d.append(f"V {base_bottom}")
        d.append(f"Q {ax - tail_len*0.4} {ay + rw*0.3} {tip_x:.1f} {tip_y:.1f}")
        d.append(f"Q {ax - tail_len*0.4} {ay - rw*0.3} {ax} {base_top}")
        d.append(f"V {by + r}")
        d.append(f"A {r} {r} 0 0 1 {bx + r} {by}")
        d.append("Z")

    else:
        # Fallback rectangular bubble without tail
        d.append(f"M {bx + r} {by}")
        d.append(f"H {bx + bw - r}")
        d.append(f"A {r} {r} 0 0 1 {bx + bw} {by + r}")
        d.append(f"V {by + bh - r}")
        d.append(f"A {r} {r} 0 0 1 {bx + bw - r} {by + bh}")
        d.append(f"H {bx + r}")
        d.append(f"A {r} {r} 0 0 1 {bx} {by + bh - r}")
        d.append(f"V {by + r}")
        d.append(f"A {r} {r} 0 0 1 {bx + r} {by}")
        d.append("Z")

    path_d = " ".join(d)

    center_x = bx + bw / 2
    first_line_y = by + pad_y + font_size * 0.88
    text_tspans = []
    for i, line_item in enumerate(lines_spec):
        text = line_item["text"]
        color = line_item.get("color", "#0f172a")
        weight = line_item.get("weight", "800")
        dy = 0 if i == 0 else line_height
        text_tspans.append(f'<tspan x="{center_x:.1f}" dy="{dy}" fill="{color}" font-weight="{weight}">{text}</tspan>')

    bubble_svg = f"""
    <g filter="url(#bubble-shadow)">
      <path class="bubble-fill" d="{path_d}" />
      <text class="text-body" x="{center_x:.1f}" y="{first_line_y:.1f}" font-size="{font_size}" text-anchor="middle">
        {"".join(text_tspans)}
      </text>
    </g>
    """
    return bubble_svg, bw, bh


def build_vertical_manga_svg(b64_list, episode_spec):
    """
    Assembles 4 cropped panels and auto-fitted speech bubbles into a unified vertical SVG.
    """
    canvas_w = 800
    margin_x = 40
    margin_y = 48
    gutter_y = 36
    panel_w = canvas_w - (margin_x * 2)  # 720
    panel_h = 540  # 4:3 Ratio
    canvas_h = margin_y * 2 + (panel_h * 4) + (gutter_y * 3)

    p_boxes = []
    for i in range(4):
        py = margin_y + i * (panel_h + gutter_y)
        p_boxes.append((margin_x, py, panel_w, panel_h))

    panels_spec = episode_spec.get("panels", [])

    svg_panels = []
    badge_colors = ["#3b82f6", "#10b981", "#ec4899", "#f59e0b"]

    for i in range(4):
        px, py, pw, ph = p_boxes[i]
        spec = panels_spec[i] if i < len(panels_spec) else {}

        img_offset_y = spec.get("image_offset_y", 0)
        img_offset_x = spec.get("image_offset_x", 0)
        img_w = spec.get("image_w", panel_w)
        img_h = spec.get("image_h", panel_h)

        # Bubble placement
        dialogue = spec.get("dialogue", [])
        if isinstance(dialogue, str):
            # Parse raw text lines
            lines_raw = dialogue.strip().split("\n")
            lines_spec = [{"text": l} for l in lines_raw]
        else:
            lines_spec = dialogue

        bubble_markup = ""
        if lines_spec:
            bx = px + spec.get("bubble_x", 160 if i != 1 else 32)
            by = py + spec.get("bubble_y", 20)
            tx = px + spec.get("target_x", 365 if i != 1 else 535)
            ty = py + spec.get("target_y", 240 if i != 1 else 190)
            tail_side = spec.get("tail_side", "auto")
            font_size = spec.get("font_size", episode_spec.get("font_size", 24))
            line_height = spec.get("line_height", episode_spec.get("line_height", int(font_size * 1.45)))

            bubble_markup, _, _ = generate_speech_bubble(
                lines_spec, bx, by, tx, ty, tail_side=tail_side, tail_len=26,
                font_size=font_size, line_height=line_height
            )

        panel_markup = f"""
  <!-- Panel {i+1} -->
  <g id="panel-{i+1}">
    <rect x="{px}" y="{py}" width="{pw}" height="{ph}" rx="14" fill="#ffffff" />
    <g clip-path="url(#p{i}-clip)">
      <image href="{b64_list[i]}" x="{px + img_offset_x}" y="{py + img_offset_y}" width="{img_w}" height="{img_h}" preserveAspectRatio="xMidYMid slice" />
    </g>
    <rect class="panel-border" x="{px}" y="{py}" width="{pw}" height="{ph}" rx="14" />
    {bubble_markup}
  </g>"""
        svg_panels.append(panel_markup)

    defs_clips = "\n    ".join([
        f'<clipPath id="p{i}-clip"><rect x="{p_boxes[i][0]}" y="{p_boxes[i][1]}" width="{panel_w}" height="{panel_h}" rx="14" /></clipPath>'
        for i in range(4)
    ])

    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {canvas_w} {canvas_h}" width="{canvas_w}" height="{canvas_h}">
  <defs>
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@700;900&amp;display=swap');
      .panel-border {{ fill: none; stroke: #0f172a; stroke-width: 6px; stroke-linejoin: round; }}
      .bubble-fill {{ fill: #ffffff; stroke: #0f172a; stroke-width: 4.5px; stroke-linejoin: round; }}
      .text-body {{ font-family: 'Noto Sans JP', 'Hiragino Sans', 'Meiryo', sans-serif; font-weight: 800; fill: #0f172a; }}
      .badge {{ font-family: 'Noto Sans JP', 'Hiragino Sans', 'Meiryo', sans-serif; font-size: 18px; font-weight: 900; fill: #ffffff; }}
    </style>
    {defs_clips}
    <filter id="bubble-shadow" x="-10%" y="-10%" width="125%" height="125%">
      <feDropShadow dx="3" dy="4" stdDeviation="4" flood-color="#000000" flood-opacity="0.14" />
    </filter>
  </defs>

  <rect width="100%" height="100%" fill="#f1f5f9" />
  {"".join(svg_panels)}
</svg>
"""
    return svg, canvas_w, canvas_h


def rasterize_svg(svg_path, png_path, canvas_w, canvas_h):
    """Rasterizes SVG to PNG using Edge headless browser."""
    edge_paths = [
        r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",
        r"C:\Program Files\Microsoft\Edge\Application\msedge.exe"
    ]
    edge_bin = next((p for p in edge_paths if os.path.exists(p)), None)
    if not edge_bin:
        print("[WARN] Microsoft Edge not found for headless rasterization.", file=sys.stderr)
        return False

    svg_uri = Path(svg_path).resolve().as_uri()
    png_path = Path(png_path).resolve()
    png_path.parent.mkdir(parents=True, exist_ok=True)

    cmd = [
        edge_bin,
        "--headless",
        "--disable-gpu",
        f"--window-size={canvas_w},{canvas_h}",
        f"--screenshot={str(png_path)}",
        svg_uri
    ]
    subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=30)
    print(f"[OK] Rasterized vertical manga to: {png_path}")
    return True


def crop_panels_from_2x3(raw_image_path):
    """Crops a 2:3 vertical single-column 4-panel raw image into 4 wide panels."""
    img = Image.open(raw_image_path).convert("RGB")
    w, h = img.size
    arr = np.array(img.convert('L'))

    # Horizontal border detection
    col_means = arr.mean(axis=0)
    left_border = [x for x in range(int(w * 0.12)) if col_means[x] < 80]
    right_border = [x for x in range(int(w * 0.88), w) if col_means[x] < 80]

    min_x = max(left_border) + 3 if left_border else int(w * 0.02)
    max_x = min(right_border) - 3 if right_border else int(w * 0.98)

    # Vertical cuts between panels
    row_means = arr.mean(axis=1)
    cuts = []
    for expected_pct in [0.025, 0.27, 0.52, 0.76, 0.98]:
        center = int(h * expected_pct)
        window = range(max(0, center - 40), min(h, center + 40))
        min_y = min(window, key=lambda y: row_means[y])
        cuts.append(min_y)

    b64_list = []
    from io import BytesIO
    for i in range(4):
        top = cuts[i] + 4
        bot = cuts[i + 1] - 4
        cropped = img.crop((min_x, top, max_x, bot))
        buf = BytesIO()
        cropped.save(buf, format="PNG")
        b64 = f"data:image/png;base64,{base64.b64encode(buf.getvalue()).decode('ascii')}"
        b64_list.append(b64)

    return b64_list


def build_2x3_fullwidth_manga_svg(b64_list, episode_spec):
    """
    Renders standard 2:3 aspect ratio (1200x1800) 4-panel vertical manga
    using full-width horizontal panels (1128x417) without side banner.
    """
    canvas_w = 1200
    canvas_h = 1800

    margin_x = 36
    margin_y = 36
    gutter_y = 20

    panel_w = canvas_w - (margin_x * 2) # 1128px
    avail_h = canvas_h - (margin_y * 2) - (gutter_y * 3) # 1668px
    panel_h = int(avail_h / 4) # 417px

    panels_dialogue = episode_spec.get("panels", [])

    svg_panels = []
    defs_clips = []

    for i in range(4):
        px = margin_x
        py = margin_y + i * (panel_h + gutter_y)
        pw = panel_w
        ph = panel_h

        d_spec = panels_dialogue[i] if i < len(panels_dialogue) else {}
        lines = d_spec.get("lines", [])
        font_size = d_spec.get("font_size", 22)
        line_height = d_spec.get("line_height", 34)

        bx = px + d_spec.get("bx", 30)
        by = py + d_spec.get("by", 20)
        tx = px + d_spec.get("tx", 400)
        ty = py + d_spec.get("ty", 200)
        tail_side = d_spec.get("tail", "auto")

        bubble_markup, _, _ = generate_speech_bubble(
            lines, bx, by, tx, ty,
            tail_side=tail_side, tail_len=26, radius=16,
            font_size=font_size, line_height=line_height
        )

        defs_clips.append(f'<clipPath id="p{i}-clip"><rect x="{px}" y="{py}" width="{pw}" height="{ph}" rx="14" /></clipPath>')

        panel_markup = f"""
  <!-- Panel {i+1} -->
  <g id="panel-{i+1}">
    <rect x="{px}" y="{py}" width="{pw}" height="{ph}" rx="14" fill="#ffffff" />
    <g clip-path="url(#p{i}-clip)">
      <image href="{b64_list[i]}" x="{px}" y="{py}" width="{pw}" height="{ph}" preserveAspectRatio="xMidYMid slice" />
    </g>
    <rect class="panel-border" x="{px}" y="{py}" width="{pw}" height="{ph}" rx="14" />
    {bubble_markup}
    <!-- Number Badge -->
    <circle cx="{px + 28}" cy="{py + 28}" r="16" fill="#0f172a" />
    <text x="{px + 28}" y="{py + 34}" class="badge" text-anchor="middle">{i+1}</text>
  </g>"""
        svg_panels.append(panel_markup)

    defs_clips_str = "\n    ".join(defs_clips)
    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {canvas_w} {canvas_h}" width="{canvas_w}" height="{canvas_h}">
  <defs>
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@700;900&amp;display=swap');
      .panel-border {{ fill: none; stroke: #0f172a; stroke-width: 5px; stroke-linejoin: round; }}
      .bubble-fill {{ fill: #ffffff; stroke: #0f172a; stroke-width: 4.5px; stroke-linejoin: round; }}
      .text-body {{ font-family: 'Noto Sans JP', 'Hiragino Sans', 'Meiryo', sans-serif; font-weight: 900; fill: #0f172a; }}
      .badge {{ font-family: 'Noto Sans JP', sans-serif; font-size: 18px; font-weight: 900; fill: #ffffff; }}
    </style>
    {defs_clips_str}
    <filter id="bubble-shadow" x="-10%" y="-10%" width="125%" height="125%">
      <feDropShadow dx="3" dy="4" stdDeviation="4" flood-color="#000000" flood-opacity="0.12" />
    </filter>
  </defs>

  <rect width="100%" height="100%" fill="#f8fafc" />
  {"".join(svg_panels)}
</svg>"""
    return svg, canvas_w, canvas_h


def run_pipeline(raw_image_path, spec_path_or_dict, output_png_path, output_svg_path=None, layout="2x3"):
    """
    Main programmatic entrypoint for daily workflows.
    Supports layout='2x3' (Twitter standard 1200x1800) and layout='1x3' (narrow strip).
    """
    if isinstance(spec_path_or_dict, (str, Path)):
        spec_file = Path(spec_path_or_dict)
        if spec_file.suffix.lower() in [".yaml", ".yml"]:
            import yaml
            with open(spec_file, "r", encoding="utf-8") as f:
                episode_spec = yaml.safe_load(f)
        else:
            with open(spec_file, "r", encoding="utf-8") as f:
                episode_spec = json.load(f)
    else:
        episode_spec = spec_path_or_dict

    if layout == "2x3":
        b64_list = crop_panels_from_2x3(raw_image_path)
        svg_content, cw, ch = build_2x3_fullwidth_manga_svg(b64_list, episode_spec)
    else:
        b64_list = crop_panels_to_b64(raw_image_path)
        svg_content, cw, ch = build_vertical_manga_svg(b64_list, episode_spec)

    output_png = Path(output_png_path)
    if not output_svg_path:
        output_svg = output_png.with_suffix(".svg")
    else:
        output_svg = Path(output_svg_path)

    output_svg.parent.mkdir(parents=True, exist_ok=True)
    output_svg.write_text(svg_content, encoding="utf-8")
    print(f"[OK] Saved SVG to: {output_svg}")

    rasterize_svg(output_svg, output_png, cw, ch)
    return output_png


def main():
    parser = argparse.ArgumentParser(description="Build vertical 4-panel manga with auto-fitted vector speech bubbles.")
    parser.add_argument("--image", required=True, help="Path to raw 4-panel image")
    parser.add_argument("--spec", required=True, help="Path to episode spec JSON or YAML file")
    parser.add_argument("--output", required=True, help="Output PNG path")
    parser.add_argument("--svg-output", help="Optional output SVG path")
    parser.add_argument("--layout", choices=["2x3", "1x3"], default="2x3", help="Manga layout format: '2x3' (Twitter 1200x1800 full-width) or '1x3' (720x2160 strip)")

    args = parser.parse_args()
    run_pipeline(args.image, args.spec, args.output, args.svg_output, layout=args.layout)


if __name__ == "__main__":
    main()

